[programs.localnet]
solana_twitter = "9jFkPjdZQVAGT4Q8XDbmt6zB54djLtXhr33tgBS31H1w"

[programs.devnet]
solana_twitter = "9jFkPjdZQVAGT4Q8XDbmt6zB54djLtXhr33tgBS31H1w"

[programs.mainnet]
solana_twitter = "9jFkPjdZQVAGT4Q8XDbmt6zB54djLtXhr33tgBS31H1w"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet-beta"
wallet = "/Users/pwarrior/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
