[programs.localnet]
solana_twitter = "C27gSx5Y6wqwb8A7STfYmMKmR62twBEuz5p1TAmfBpR5"

[programs.devnet]
solana_twitter = "C27gSx5Y6wqwb8A7STfYmMKmR62twBEuz5p1TAmfBpR5"

[programs.mainnet]
solana_twitter = "C27gSx5Y6wqwb8A7STfYmMKmR62twBEuz5p1TAmfBpR5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/Users/pwarrior/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
