[programs.localnet]
solana_twitter = "2b6VCZo9YTtPd1yALGY4M8jkhGTRXm3GBgssAsfJiVGQ"

[programs.devnet]
solana_twitter = "2b6VCZo9YTtPd1yALGY4M8jkhGTRXm3GBgssAsfJiVGQ"

[programs.mainnet]
solana_twitter = "2b6VCZo9YTtPd1yALGY4M8jkhGTRXm3GBgssAsfJiVGQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/pwarrior/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
